project:
  type: default
  output-dir: docs-rendered
  render: 
    - docs-working/methods_environmental_conditions.qmd
    - docs-working/methods_parameterisation.qmd
    - docs-working/results_ambient_growth.qmd
    - docs-working/results_ambient_growth_lims.qmd
    - docs-working/results_supplemented_growth.qmd
    - docs-working/all_for_manuscript.qmd

format:
  html:
    theme: simplex
    css: ["docs-working/extra.css"]
    embed-resources: true
    code-fold: true
    code-overflow: wrap
    toc: true
    toc-expand: true
    toc-location: left
    toc-depth: 4
    lang: en-GB
    grid:
      sidebar-width: 300px
      body-width: 1250px
      margin-width: 200px
      gutter-width: 2em
        
execute:
  eval: true
  cache: true # quarto render .\documentation\ --cache-refresh

bibliography: ["docs-working/refs.bib", "docs-working/manual-refs.bib"]

knitr: 
  opts_chunk:
    fig.align: center
    fig.height: 8
    fig.width: 6.5
