{
  "hash": "a17789ad4c7702a2f72657ddf785d87a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Investigating the bioremediation potential of seaweed aquaculture across Australia\ndate: last-modified\nbibliography: [\"refs.bib\", \"manual-refs.bib\"]\n\nformat:\n  html:\n    theme: simplex\n    css: [\"extra.css\"]\n    code-fold: true\n    code-overflow: wrap\n    toc: true\n    toc-expand: true\n    toc-location: left\n    toc-depth: 4\n    lang: en-GB\n    grid:\n      sidebar-width: 300px\n      body-width: 1250px\n      margin-width: 200px\n      gutter-width: 2em\n        \nexecute:\n  eval: false\n  cache: true\n\nknitr: \n  opts_chunk:\n    fig.align: center\n    fig.height: 9.5\n    fig.width: 6.5\n---\n\n::: {.cell .hidden layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\n# You need quarto to generate this markdown - install here: https://quarto.org/docs/get-started/\n# This markdown uses the acronyms extension - install by entering quarto add rchaput/acronyms@master into the terminal\n# This markdown uses TinyTex for PDF rendering - install with tinytex::install_tinytex()\n\nlibrary(stringr)\nlibrary(units)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: package 'units' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nudunits database from C:/Users/treimer/AppData/Local/R/cache/R/renv/cache/v5/windows/R-4.4/x86_64-w64-mingw32/units/0.8-7/5d0b024902d5da97a2b64f002e92a869/units/share/udunits/udunits2.xml\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(targets)\nlibrary(tarchetypes)\nlibrary(macrogrow)\nlibrary(ozmaps)\nlibrary(arrow)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'arrow'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:utils':\n\n    timestamp\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(gganimate)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required package: ggplot2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(magrittr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'magrittr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:arrow':\n\n    is_in\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(terra)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nterra 1.8.50\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'terra'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:magrittr':\n\n    extract, inset\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:gganimate':\n\n    animate\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:arrow':\n\n    buffer\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(tidyterra)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: package 'tidyterra' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'tidyterra'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:stats':\n\n    filter\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(here)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nhere() starts at C:/Users/treimer/Documents/R-temp-files/modelling-asparagopsis\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(lubridate)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'lubridate'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:terra':\n\n    intersect, union\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:arrow':\n\n    duration\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:base':\n\n    date, intersect, setdiff, union\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(tidyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'tidyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:terra':\n\n    extract\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:magrittr':\n\n    extract\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(cowplot)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'cowplot'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:lubridate':\n\n    stamp\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(purrr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'purrr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:magrittr':\n\n    set_names\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(conflicted)\nconflicts_prefer(dplyr::select, dplyr::filter)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n[conflicted] Will prefer dplyr::select over any other package.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n[conflicted] Will prefer dplyr::filter over any other package.\n```\n\n\n:::\n:::\n\n::: {.cell .hidden layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\n# source(file.path(base_path, \"R\", \"other-functions.R\"))\nspec_store <- here() %>% file.path(\"targets_outputs\", \"_species\")\nenvi_store <- here() %>% file.path(\"targets_outputs\", \"_env_inputs\")\nruns_store <- here() %>% file.path(\"targets_outputs\", \"_model_running\")\nspec_data <- here() %>% file.path(\"data\", \"processed_species\")\nenvi_data <- here() %>% file.path(\"data\", \"processed_env_inputs\")\nruns_data <- here() %>% file.path(\"data\", \"processed_model_running\")\n\nbounds <- file.path(envi_data, \"states_bbox.qs\") %>% qs::qread()\n\nprettyplot <- theme_classic() +\n  theme(text = element_text(family = \"serif\", size = 11, colour = \"black\"),\n        legend.position = \"none\",\n        axis.title.y = element_text(vjust = 1.5),\n        axis.title.x = element_text(vjust = 1.5),\n        legend.title = element_blank())\nenv_plot <- prettyplot + theme(aspect.ratio = 0.55)\n\nfind_read <- function(path, pattern) {\n  fnm <- list.files(path, full.names = T) %>% str_subset(pattern)\n  if (all(str_detect(fnm, \".qs\"))) {dat <- purrr::map(fnm, qs::qread)}\n  if (all(str_detect(fnm, \".parquet\"))) {dat <- purrr::map_dfr(fnm, arrow::read_parquet)}\n  return(dat)\n}\n\nnitrogen_lab <- expression(\"Concentration (\"*mu*\"M N)\")\nnitrate_lab <- expression(\"Nitrate concentration (\"*mu*\"M NO\"[3]*\")\")\nammonium_lab <- expression(\"Ammonium concentration (\"*mu*\"M NH\"[4]^+\")\")\n\n# Allows using \"units\" package to convert between moles and g of nitrogen ONLY\nremove_unit(\"mol\")\ninstall_unit(\"mol\", \"14.0067 g\")\n\nprettynum <- function(num, sigfig=2) {format(round(as.numeric(num), sigfig), nsmall=1, big.mark=\",\")}\n\nspecies_pal <- c(\"red3\", \"dodgerblue3\")\ndepths_pal <- c(\"green3\", \"#FF8247\", \"dodgerblue3\", \"grey56\")\nscens_pal_1 <- c(\"#292928\", \"dodgerblue3\", \"#66a61e\", \"#e7298a\", \"#e6ab02\")\nscens_pal_2 <- c(\"dodgerblue3\", \"#66a61e\", \"#e7298a\", \"#e6ab02\")\nstates_pal <- c(\n  \"NTE\" = \"#d95f02\", \"Northern Territory\" = \"#d95f02\",\n  \"QLD\" = \"#e6ab02\", \"Queensland\" = \"#e6ab02\",\n  \"NSW\" = \"#7570b3\", \"New South Wales\" = \"#7570b3\",\n  \"SAU\" = \"#1b9e77\", \"South Australia\" = \"#1b9e77\",\n  \"TAS\" = \"#66a61e\", \"Tasmania\" = \"#66a61e\",\n  \"VIC\" = \"#e7298a\", \"Victoria\" = \"#e7298a\",\n  \"WAN\" = \"#a6761d\", \"Western Australia (N)\" = \"#a6761d\",\n  \"WAS\" = \"#666666\", \"Western Australia (S)\" = \"#666666\"\n)\nlims_pal <- c(\"No_limit\" = \"black\", \"T_lim\" = \"#e7298a\", \"I_lim\" = \"#e6ab02\", \"S_lim\" = \"#7570b3\", \n              \"Q_lim\" = \"#66a61e\", \"Nf_loss\" = \"#1b9e77\", \"Ns_loss\" = \"#e7298a\")\nstates <- tar_read(states, store = runs_store)\nstates_ord <- c(\"NTE\", \"QLD\", \"NSW\", \"SAU\", \"TAS\", \"VIC\", \"WAN\", \"WAS\")\nstates_lng <- c(\"Northern Territory\", \"Queensland\", \"New South Wales\", \"South Australia\", \"Tasmania\", \"Victoria\", \"Western Australia (N)\", \"Western Australia (S)\")\n```\n:::\n\n\n\n# Methods {#sec-methods}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden  code-summary=\"Load in all the BARRA-C2 cells being used, with their coordinates.\"}\ncell_coords <- find_read(envi_data, \"cell_coords\") %>% \n  mutate(state = factor(state, levels = states_ord)) %>% \n  dplyr::select(-layer)\ncells_included <- find_read(runs_data, \"include\")\ncells_omitted <- find_read(runs_data, \"omit\")\n\ntotals <- cell_coords %>% \n  filter(!cell_no %in% cells_omitted) %>% \n  group_by(state) %>% \n  reframe(cells = n())\n```\n:::\n\n\n\nThe waters around Australia were divided into 95418 cells for this analysis: \n5045 in Victoria, \n5480 in New South Wales, \n21956 in Queensland, \n11451 in South Australia, \n29062 in Western Australia (divided into \n13794 cells in the north and \n15268 in the south), \n10185 in Tasmania, and \n12239 in the Northern Territory. \n\n\n\n::: {#cell-fig-states-map .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nggplot(cell_coords, aes(x = longitude, y = latitude, fill = state)) +\n  geom_raster() +\n  geom_sf(data = ozmap_data(data = \"states\"), inherit.aes = F) +\n  coord_sf(xlim = c(bounds[[\"AUS\"]][\"lonmin\"], bounds[[\"AUS\"]][\"lonmax\"]),\n           ylim = c(bounds[[\"AUS\"]][\"latmin\"], bounds[[\"AUS\"]][\"latmax\"])) +\n  scale_x_continuous(breaks = seq(100, 160, 5)) +\n  scale_y_continuous(breaks = seq(-5, -45, -5)) +\n  scale_colour_manual(values = states_pal) +\n  scale_fill_manual(values = states_pal) +\n  labs(x = \"Longitude\", y = \"Latitude\") +\n  prettyplot +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: No shared levels found between `names(values)` of the manual scale and the\ndata's colour values.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Map showing the area included this analysis, with colours indicating the different states. The ~60 km coastline buffer includes 95,418 cells approximately 4 x 4 km each.](manuscript_files/figure-html/fig-states-map-1.png){#fig-states-map fig-align='center' width=624}\n:::\n:::\n\n\n\n## Environmental inputs {#sec-envinputs}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\ncell_input_all <- find_read(envi_data, \"cell_input_all\") %>% \n  mutate(state = factor(state, levels = states_ord, labels = states_lng))\n\nT_input <- cell_input_all %>% \n  select(cell_no, state, yday, T_input)\n\n(T_means <- T_input %>% \n  group_by(state) %>% \n  reframe(mean = mean(T_input, na.rm = T),\n          max = max(T_input, na.rm = T),\n          min = min(T_input, na.rm = T)) %>% \n  mutate(variable = \"T_input\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  state                  mean   max   min variable\n  <fct>                 <dbl> <dbl> <dbl> <chr>   \n1 Northern Territory     28.7  37.9 18.9  T_input \n2 Queensland             26.7  36.1 12.6  T_input \n3 New South Wales        21.8  30.8  7.77 T_input \n4 South Australia        17.3  31.8  7.12 T_input \n5 Tasmania               15.2  24.3  3.95 T_input \n6 Victoria               16.1  29.7  6.48 T_input \n7 Western Australia (N)  27.7  40.9 17.3  T_input \n8 Western Australia (S)  20.3  38.7  9.02 T_input \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nI_input <- cell_input_all %>% \n  select(cell_no, state, yday, I_input)\n\n(I_means <- I_input %>% \n  group_by(state) %>% \n  reframe(mean = mean(I_input, na.rm = T),\n          max = max(I_input, na.rm = T),\n          min = min(I_input, na.rm = T)) %>% \n  mutate(variable = \"I_input\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  state                  mean   max   min variable\n  <fct>                 <dbl> <dbl> <dbl> <chr>   \n1 Northern Territory     362.  639.  5.04 I_input \n2 Queensland             311.  655. 14.1  I_input \n3 New South Wales        278.  650. 14.1  I_input \n4 South Australia        280.  734.  6.70 I_input \n5 Tasmania               207.  696.  2.98 I_input \n6 Victoria               232.  678.  5.78 I_input \n7 Western Australia (N)  446.  705. 31.8  I_input \n8 Western Australia (S)  318.  736.  8.17 I_input \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nK_input <- cell_input_all %>% \n  select(cell_no, state, yday, Kd_490)\n\n(K_means <- K_input %>% \n  group_by(state) %>% \n  reframe(mean = mean(Kd_490, na.rm = T),\n          max = max(Kd_490, na.rm = T),\n          min = min(Kd_490, na.rm = T)) %>% \n  mutate(variable = \"Kd_490\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  state                   mean   max    min variable\n  <fct>                  <dbl> <dbl>  <dbl> <chr>   \n1 Northern Territory    0.118   6.00 0.0184 Kd_490  \n2 Queensland            0.102   6.00 0.0168 Kd_490  \n3 New South Wales       0.0866  6.00 0.0172 Kd_490  \n4 South Australia       0.101   6.00 0.0172 Kd_490  \n5 Tasmania              0.0936  6.00 0.0180 Kd_490  \n6 Victoria              0.133   6.00 0.0192 Kd_490  \n7 Western Australia (N) 0.102   6.00 0.0176 Kd_490  \n8 Western Australia (S) 0.0595  6.00 0.0170 Kd_490  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nS_input <- cell_input_all %>% \n  select(cell_no, state, yday, S_input)\n\n(S_means <- S_input %>% \n  group_by(state) %>% \n  reframe(mean = mean(S_input, na.rm = T),\n          max = max(S_input, na.rm = T),\n          min = min(S_input, na.rm = T)) %>% \n  mutate(variable = \"S_input\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  state                  mean   max   min variable\n  <fct>                 <dbl> <dbl> <dbl> <chr>   \n1 Northern Territory     34.5  35.6  32.8 S_input \n2 Queensland             35.0  35.9  32.9 S_input \n3 New South Wales        35.5  35.7  35.1 S_input \n4 South Australia        35.9  37.2  35.2 S_input \n5 Tasmania               35.4  35.7  34.9 S_input \n6 Victoria               35.5  35.8  35.3 S_input \n7 Western Australia (N)  34.9  35.9  34.2 S_input \n8 Western Australia (S)  35.7  36.4  35.0 S_input \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nUV_input <- cell_input_all %>% \n  select(cell_no, state, yday, UV_input)\n\n(UV_means <- UV_input %>% \n  group_by(state) %>% \n  reframe(mean = mean(UV_input, na.rm = T),\n          max = max(UV_input, na.rm = T),\n          min = min(UV_input, na.rm = T)) %>% \n  mutate(variable = \"UV_input\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  state                   mean   max       min variable\n  <fct>                  <dbl> <dbl>     <dbl> <chr>   \n1 Northern Territory    0.0647 0.348 0.0000366 UV_input\n2 Queensland            0.144  1.06  0.0000336 UV_input\n3 New South Wales       0.370  1.46  0.000455  UV_input\n4 South Australia       0.0786 0.689 0.0000366 UV_input\n5 Tasmania              0.0859 0.622 0.0000262 UV_input\n6 Victoria              0.0954 0.785 0.000114  UV_input\n7 Western Australia (N) 0.0694 0.559 0.0000110 UV_input\n8 Western Australia (S) 0.135  0.843 0.0000548 UV_input\n```\n\n\n:::\n:::\n\n\n\nMean daily temperature ranged from \n15.2 in Tasmania to \n28.7 in Northern Territory,\nwith a mean across states of 21.7. \n\n\n\n::: {#cell-fig-T-input .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nT_input_state <- T_input %>%\n  group_by(state, yday) %>% \n  reframe(value = mean(T_input, na.rm = T),\n          sd = sd(T_input, na.rm = T))\n\n(\n  p_input_state_av <- T_input_state %>% \n    ggplot(aes(x = yday, y = value, ymin = value-sd, ymax = value+sd, colour = state, fill = state)) +\n    geom_line(linewidth = 0.75) +\n    geom_ribbon(alpha = 0.35, linewidth = 0.25) +\n    facet_wrap(facets = vars(state), ncol = 2) +\n    scale_y_continuous(breaks = seq(0, 40, 5), limits = c(10, 35)) +\n    scale_colour_manual(values = states_pal) +\n    scale_fill_manual(values = states_pal) +\n    env_plot +\n    labs(x = \"Day of the year\", y = expression(\"Temperature (\"*degree*\"C)\"))\n)\n```\n\n::: {.cell-output-display}\n![Summary of temperature values across the year within each state, averaged across 2019-2023. Bold lines show the mean across all cells within each state while ribbons show the standard deviation between cells.](manuscript_files/figure-html/fig-T-input-1.png){#fig-T-input fig-align='center' width=624}\n:::\n:::\n\n\n\nMean daily irradiance ranged from \n207 in Tasmania to \n446 in Western Australia (N),\nwith a mean across states of 304. \n\n\n\n::: {#cell-fig-I-input .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nI_input_state <- I_input %>%\n  group_by(state, yday) %>% \n  reframe(value = mean(I_input, na.rm = T),\n          sd = sd(I_input, na.rm = T))\n\np_input_state_av %+% I_input_state +\n  scale_y_continuous(breaks = seq(0, 1600, 150), limits = c(0, 750)) +\n  labs(x = \"Day of the year\", y = expression(\"Irradiance (photons m\"^-2*\" s\"^-1*\")\")) \n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nScale for y is already present.\nAdding another scale for y, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Summary of irradiance values across the year within each state, averaged across 2019-2023. Bold lines show the mean across all cells within each state while ribbons show the standard deviation between cells. ](manuscript_files/figure-html/fig-I-input-1.png){#fig-I-input fig-align='center' width=624}\n:::\n:::\n\n\n\nMean daily values for the light attenuation coefficient in water ranged from \n5.95 $\\times 10^2$ in \nWestern Australia (S) to \n1.33 $\\times 10$ in \nVictoria,\nwith a mean across states of 9.95 $\\times 10^2$. \n\n\n\n::: {#cell-fig-kW-input .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nK_input_state <- K_input %>%\n  group_by(state, yday) %>% \n  reframe(value = mean(Kd_490, na.rm = T),\n          sd = sd(Kd_490, na.rm = T)) %>% \n  mutate(sd = case_when(sd > value ~ value, T ~ sd))\n\np_input_state_av %+% K_input_state +\n  scale_y_continuous(breaks = seq(0, 0.6, 0.1), limits = c(0, 0.6)) +\n  labs(x = \"Day of the year\", y = expression(\"Light attenuation coefficient (m\"^-1*\" )\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nScale for y is already present.\nAdding another scale for y, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Summary of irradiance values across the year within each state, averaged across 2019-2023. Bold lines show the mean across all cells within each state while ribbons show the standard deviation between cells. ](manuscript_files/figure-html/fig-kW-input-1.png){#fig-kW-input fig-align='center' width=624}\n:::\n:::\n\n\n\nMean daily salinity ranged from \n34.5 in Northern Territory to \n35.9 in South Australia,\nwith a mean across states of 35.3. \n\n\n\n::: {#cell-fig-S-input .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nS_input_state <- S_input %>%\n  group_by(state, yday) %>% \n  reframe(value = mean(S_input, na.rm = T),\n          sd = sd(S_input, na.rm = T))\n\np_input_state_av %+% S_input_state +\n  scale_y_continuous(breaks = seq(30, 40, 0.5), limits = c(34, 36.5)) +\n  labs(x = \"Day of the year\", y = expression(\"Salinity (g L\"^-1*\")\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nScale for y is already present.\nAdding another scale for y, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Summary of salinity values across the year within each state, averaged across 2019-2023 and all depths < 25 m. Bold lines show the mean across all cells within each state while ribbons show the standard deviation between cells.](manuscript_files/figure-html/fig-S-input-1.png){#fig-S-input fig-align='center' width=624}\n:::\n:::\n\n\n\nMean daily water velocity ranged from \n0.06 in Northern Territory to \n0.37 in New South Wales,\nwith a mean across states of 0.13. \n\n\n\n::: {#cell-fig-UV-input .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nUV_input_state <- UV_input %>%\n  group_by(state, yday) %>% \n  reframe(value = mean(UV_input, na.rm = T),\n          sd = sd(UV_input, na.rm = T)) %>% \n  mutate(sd_min = case_when(sd > value ~ value, T ~ sd))\n\n(\n  p_input_state_av <- UV_input_state %>% \n    ggplot(aes(x = yday, y = value, ymin = value-sd_min, ymax = value+sd, colour = state, fill = state)) +\n    geom_line(linewidth = 0.75) +\n    geom_ribbon(alpha = 0.35, linewidth = 0.25) +\n    facet_wrap(facets = vars(state), ncol = 2) +\n    scale_y_continuous(breaks = seq(0, 1, 0.2), limits = c(-0.01, 1)) +\n    scale_colour_manual(values = states_pal) +\n    scale_fill_manual(values = states_pal) +\n    env_plot +\n    labs(x = \"Day of the year\", y = expression(\"Water velocity (m s\"^-1*\")\"))\n)\n```\n\n::: {.cell-output-display}\n![Summary of water velocity values across the year within each state, averaged across 2019-2023 and all depths < 25 m. Bold lines show the mean across all cells within each state while ribbons show the standard deviation between cells.](manuscript_files/figure-html/fig-UV-input-1.png){#fig-UV-input fig-align='center' width=624}\n:::\n:::\n\n\n\n## Nitrogen {#sec-nitrogen}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nrefstation_locations <- here() %>% \n  file.path(\"data\", \"nitrogen\", \"refstation_locations.parquet\") %>% \n  arrow::read_parquet() %>% \n  rename(name = StationName) %>% \n  dplyr::select(-code)\n\noutfall_locations <- here() %>% \n  file.path(\"data_raw\", \"national-outfall-database\", \"data-output\", \"outflow_site_locations.parquet\") %>% \n  arrow::read_parquet() %>% \n  rename(lon = longitude,\n         lat = latitude) %>% \n  dplyr::select(-state)\n\nN_locations <- rbind(\n  outfall_locations %>% mutate(type = \"outfall\"),\n  refstation_locations %>% mutate(type = \"refstation\")\n) %>% \n  mutate(name = as.character(name),\n         state = case_when(\n    lon > bounds[[\"SAU\"]][\"lonmin\"] & lon <= bounds[[\"SAU\"]][\"lonmax\"] & \n      lat > bounds[[\"SAU\"]][\"latmin\"] & lat <= bounds[[\"SAU\"]][\"latmax\"]  ~ \"SAU\",\n    lon > bounds[[\"QLD\"]][\"lonmin\"] & lon <= bounds[[\"QLD\"]][\"lonmax\"] & \n      lat > bounds[[\"QLD\"]][\"latmin\"] & lat <= bounds[[\"QLD\"]][\"latmax\"]  ~ \"QLD\",\n    lon > bounds[[\"WAS\"]][\"lonmin\"] & lon <= bounds[[\"WAS\"]][\"lonmax\"] & \n      lat > bounds[[\"WAS\"]][\"latmin\"] & lat <= bounds[[\"WAS\"]][\"latmax\"]  ~ \"WAS\",\n    lon > bounds[[\"WAN\"]][\"lonmin\"] & lon <= bounds[[\"WAN\"]][\"lonmax\"] & \n      lat > bounds[[\"WAN\"]][\"latmin\"] & lat <= bounds[[\"WAN\"]][\"latmax\"]  ~ \"WAN\",\n    lon > bounds[[\"VIC\"]][\"lonmin\"] & lon <= bounds[[\"VIC\"]][\"lonmax\"] & \n      lat > bounds[[\"VIC\"]][\"latmin\"] & lat <= bounds[[\"VIC\"]][\"latmax\"]  ~ \"VIC\",\n    lon > bounds[[\"NSW\"]][\"lonmin\"] & lon <= bounds[[\"NSW\"]][\"lonmax\"] & \n      lat > bounds[[\"NSW\"]][\"latmin\"] & lat <= bounds[[\"NSW\"]][\"latmax\"]  ~ \"NSW\",\n    lon > bounds[[\"NTE\"]][\"lonmin\"] & lon <= bounds[[\"NTE\"]][\"lonmax\"] & \n      lat > bounds[[\"NTE\"]][\"latmin\"] & lat <= bounds[[\"NTE\"]][\"latmax\"]  ~ \"NTE\",\n    lon > bounds[[\"TAS\"]][\"lonmin\"] & lon <= bounds[[\"TAS\"]][\"lonmax\"] & \n      lat > bounds[[\"TAS\"]][\"latmin\"] & lat <= bounds[[\"TAS\"]][\"latmax\"]  ~ \"TAS\",\n    TRUE ~ NA\n  ),\n  state = factor(state, levels = states_ord)) %>% \n  relocate(state, .before = name) %>% \n  rename(latitude = lat,\n         longitude = lon)\n\nrefstation_locations <- filter(N_locations, type == \"refstation\")\noutfall_locations <- filter(N_locations, type == \"outfall\")\n```\n:::\n\n::: {#cell-fig-N-data-locations .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nggplot(N_locations, aes(x = longitude, y = latitude, color = state, shape = type)) +\n  geom_sf(data = ozmap_data(data = \"states\"), inherit.aes = F) +\n  coord_sf(xlim = c(bounds[[\"AUS\"]][\"lonmin\"], bounds[[\"AUS\"]][\"lonmax\"]),\n           ylim = c(bounds[[\"AUS\"]][\"latmin\"], bounds[[\"AUS\"]][\"latmax\"])) +\n  geom_point(size = 3.5) +\n  scale_shape_manual(values = c(20, 13)) +\n  # scale_colour_manual(values = states_pal, labels = states_lng, na.value = \"black\") +\n  scale_color_brewer(palette = \"Dark2\") +\n  scale_x_continuous(breaks = seq(100, 160, 5)) +\n  scale_y_continuous(breaks = seq(-5, -45, -5)) +\n  labs(x = \"Longitude\", y = \"Latitude\") +\n  prettyplot +\n  theme(legend.position = \"none\")\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nall_cells <- sum(totals$cells)\n\ncells_by_station_refstations <- file.path(envi_data, \"cells_by_station_refstations.parquet\") %>% read_parquet() %>% mutate(ncp = 100*nc/all_cells)\n# stations_by_cell_refstations <- file.path(envi_data, \"stations_by_cell_refstations.parquet\") %>% read_parquet() %>% mutate(nsp = 100*ns/all_cells)\ncells_by_station_outfalls <- file.path(envi_data, \"cells_by_station_outfalls.parquet\") %>% read_parquet() %>% mutate(ncp = 100*nc/all_cells)\nstations_by_cell_outfalls <- file.path(envi_data, \"stations_by_cell_outfalls.parquet\") %>% read_parquet() %>% \n  group_by(ns) %>% \n  reframe(nc = n()) %>% \n  mutate(ncp = 100*nc/all_cells)\n\n# levels(cells_by_station_refstations$StationName)\n```\n:::\n\n\n\nMatching model cells to their two nearest reference stations resulted in \n40.8% of cells using data from Darwin, \n31% using data from Kangaroo Island, \n24.7% using data from Maria Island, \n15.8% from North Stradbroke Island, \n20.6% using data from Port Hacking, \n31% using data from Rottnest Island, and \n36% using data from Yongala. \n\nThere were \n8 outfall stations in South Australia, \n9 in southern Western Australia, \n1 in northern Western Australia, \n32 in southern New South Wales, \n29 in Queensland, \n18 in Victoria, \n32 in Tasmania, and\n4 in the Northern Territory.\n\nMatching cells to outfall stations within 48 km resulted in \n6.8% of cells using data from one outfall site,\n2.8, 1.8% of cells using data from two or three sites,\n0.8, 0.4% of cells using data from three or four sites,\n0.4, 0.1, 0.1% of cells using data from six to eight sites, and \n0.1, 0.1, 0, 0% of cells using data from nine to twelve sites.\nThe remaining \n86.6% of cells did not use data from any outfall sites. \n\n\n\n::: {#cell-fig-example-N-input .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nBARRA_C2_cell_nos <- file.path(envi_data, \"BARRA_C2_cell_nos.qs\") %>% qs::qread()\nind <- which(BARRA_C2_cell_nos == 753076)\n\ncombined_data <- envi_data %>% \n  list.files(full.names = T) %>% \n  str_subset(\"combined_N_data\") %>% \n  purrr::map_dfr(arrow::read_parquet) %>% \n  filter(cell_no == 753076) %>% \n  mutate(data_source = as.factor(data_source),\n         indicator = factor(indicator, levels = c(\"nitrate_nitrite\", \"ammonia\")),\n         value = value %>% set_units(\"mg m-3\") %>% set_units(\"umol L-1\"))\n\ncell_input_eg <- cell_input_all %>% \n  filter(cell_no == 753076) %>% \n  select(yday, Ni_input, Am_input) %>% \n  pivot_longer(names_to = \"indicator\", values_to = \"value\", cols = c(Ni_input, Am_input)) %>% \n  mutate(indicator = factor(indicator, \n                            levels = c(\"Ni_input\", \"Am_input\"), \n                            labels = c(\"nitrate_nitrite\", \"ammonia\")),\n         value = value %>% set_units(\"mg m-3\") %>% set_units(\"umol L-1\"))\n\n# combined_mean_sd <- envi_data %>% \n#   list.files(full.names = T) %>% \n#   str_subset(\"combined_N_mean_sd\") %>% \n#   purrr::map_dfr(arrow::read_parquet) %>% \n#   filter(cell_no == 753076)\n# \n# combined_parameters <- envi_data %>% \n#   list.files(full.names = T) %>% \n#   str_subset(\"combined_N_parameters\") %>% \n#   purrr::map_dfr(arrow::read_parquet) %>% \n#   filter(cell_no == 753076)\n  \nggplot(combined_data, \n       aes(x = yday, y = value, fill = as.factor(data_source), colour = as.factor(data_source), size = weight)) +\n  geom_point(shape = 21, alpha = 0.35) +\n  facet_wrap(facets = vars(indicator), nrow = 2) +\n  geom_line(data = cell_input_eg, aes(x = yday, y = value), inherit.aes = F) +\n  scale_fill_manual(values = c(\"orange\", \"steelblue\")) +\n  scale_colour_manual(values = c(\"orange\", \"steelblue\")) +\n  # scale_y_continuous(limits = c(0, 3.5), breaks = seq(0, 4, 0.5)) +\n  env_plot +\n  theme(strip.text = element_blank(), aspect.ratio = 0.55) +\n  labs(x = \"Day of the year\", y = nitrogen_lab)\n```\n\n::: {.cell-output-display}\n![An example of the daily nitrate (top) and ammonium (bottom) input and data for a single cell in New South Wales. Black lines show the input driving the growth model (constructed curve), blue dots show data from the nearest reference station (Port Hacking) and orange dots show distance-weighted data from the three nearest outfall points (Bateman’s Bay, Bermagui, and Bombo).](manuscript_files/figure-html/fig-example-N-input-1.png){#fig-example-N-input fig-align='center' width=624}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nNi_input <- cell_input_all %>% \n  select(cell_no, state, yday, Ni_input)\n\n(Ni_means <- Ni_input %>% \n  group_by(state) %>% \n  reframe(mean = mean(Ni_input, na.rm = T),\n          max = max(Ni_input, na.rm = T),\n          min = min(Ni_input, na.rm = T)) %>% \n  mutate(variable = \"Ni_input\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  state                  mean   max   min variable\n  <fct>                 <dbl> <dbl> <dbl> <chr>   \n1 Northern Territory     3.68 20.4   0    Ni_input\n2 Queensland             1.64 92.1   0    Ni_input\n3 New South Wales        9.40 40.2   0    Ni_input\n4 South Australia        6.28 75.4   0    Ni_input\n5 Tasmania              20.9  36.7   7.74 Ni_input\n6 Victoria              19.5  98.1   0    Ni_input\n7 Western Australia (N)  3.00  7.86  0    Ni_input\n8 Western Australia (S)  1.78 24.3   0    Ni_input\n```\n\n\n:::\n:::\n\n\n\nMean daily water velocity ranged from \n1.64 in Queensland to \n20.86 in Tasmania,\nwith a mean across states of 8.26. \n\n\n\n::: {#cell-fig-Ni-input .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nNi_input_state <- Ni_input %>%\n  group_by(state, yday) %>% \n  reframe(value = mean(Ni_input, na.rm = T),\n          sd = sd(Ni_input, na.rm = T))\n\n(\n  p_input_state_av <- Ni_input_state %>% \n    ggplot(aes(x = yday, y = value, ymin = value-sd, ymax = value+sd, colour = state, fill = state)) +\n    geom_line(linewidth = 0.75) +\n    geom_ribbon(alpha = 0.35, linewidth = 0.25) +\n    facet_wrap(facets = vars(state), ncol = 2) +\n    # scale_y_continuous(breaks = seq(0, 40, 5), limits = c(10, 35)) +\n    scale_colour_manual(values = states_pal) +\n    scale_fill_manual(values = states_pal) +\n    env_plot +\n    labs(x = \"Day of the year\", y = nitrate_lab)\n)\n```\n\n::: {.cell-output-display}\n![Summary of nitrate concentration values across the year within each state, averaged across 2019-2023. Bold lines show the mean across all cells within each state while ribbons show the standard deviation between cells.](manuscript_files/figure-html/fig-Ni-input-1.png){#fig-Ni-input fig-align='center' width=624}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nAm_input <- cell_input_all %>% \n  select(cell_no, state, yday, Am_input)\n\n(Am_means <- Am_input %>% \n  group_by(state) %>% \n  reframe(mean = mean(Am_input, na.rm = T),\n          max = max(Am_input, na.rm = T),\n          min = min(Am_input, na.rm = T)) %>% \n  mutate(variable = \"Am_input\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 5\n  state                  mean   max    min variable\n  <fct>                 <dbl> <dbl>  <dbl> <chr>   \n1 Northern Territory     2.35  4.94 0.366  Am_input\n2 Queensland             1.62  5.39 0.0830 Am_input\n3 New South Wales        3.33  5.76 1.07   Am_input\n4 South Australia        2.64  5.18 0.691  Am_input\n5 Tasmania               2.09 14.2  0      Am_input\n6 Victoria               2.76 73.0  0      Am_input\n7 Western Australia (N)  1.92  4.22 0.408  Am_input\n8 Western Australia (S)  1.33  3.01 0.428  Am_input\n```\n\n\n:::\n:::\n\n\n\nMean daily water velocity ranged from \n1.33 in Western Australia (S) to \n3.33 in New South Wales,\nwith a mean across states of 2.26. \n\n\n\n::: {#cell-fig-Am-input .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nAm_input_state <- Am_input %>%\n  group_by(state, yday) %>% \n  reframe(value = mean(Am_input, na.rm = T),\n          sd = sd(Am_input, na.rm = T))\n\np_input_state_av %+% Am_input_state +\n  # scale_y_continuous(breaks = seq(30, 40, 0.5), limits = c(34, 36.5)) +\n  labs(x = \"Day of the year\", y = ammonium_lab)\n```\n\n::: {.cell-output-display}\n![Summary of ammonium concentration values across the year within each state, averaged across 2019-2023. Bold lines show the mean across all cells within each state while ribbons show the standard deviation between cells.](manuscript_files/figure-html/fig-Am-input-1.png){#fig-Am-input fig-align='center' width=624}\n:::\n:::\n\n\n\n## Sensitivity conditions\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nlibrary(patchwork)\n\nculture_depths <- tar_read(culture_depths, store = spec_store)\nfactors <- tar_read(factors, store = spec_store)\n\nstate_input_timeseries <- envi_data %>% \n  list.files(full.names = T) %>% \n  str_subset(\"state_input_timeseries\") %>% \n  purrr::map_dfr(arrow::read_parquet) %>% \n  filter(yday <= 365)\n\nsens_cond <- file.path(spec_data, \"sensitivity_conditions.parquet\") %>% \n  arrow::read_parquet()\n```\n:::\n\n\n\nCulture depths tested were 0.5, 2.5, 5, 10 m below the surface, with a \n\nSensitivity runs started on the first of every month to cover annual variability, for 12 runs per year, with the same mean annual conditions looping from December to January. Sensitivity runs were conducted at culture depths of 0.5 m, 2 m, 3.5 m, and 5 m below the surface with a light attenuation coefficient of 0.65 (clear water). The canopy was always 2.5 m in height, and the total water column depth was always 50 m.\nCurves for temperature, surface irradiance, salinity, water velocity, nitrate and ammonium were constructed to capture “typical” conditions based on daily means of each state from 2019-2023. This resulted in two sensitivity curves for temperature and a single sensitivity curve for irradiance, water velocity, salinity, nitrate and ammonium (fig-sens-altogether). \n\n\n\n::: {#cell-fig-sens-altogether .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\np1 <- sens_cond %>% \n  dplyr::filter(t <= 365) %>% \n  ggplot(aes(x = t, y = T_input, linetype = as.factor(T_level))) +\n  geom_line(linewidth = 0.75) +\n  geom_line(data = state_input_timeseries, aes(x = yday, y = T_input_mean, colour = state), linetype = \"dotted\", inherit.aes = F) +\n  scale_y_continuous(breaks = seq(10, 35, 5), limits = c(10, 33)) +\n  labs(y = expression(\"Temperature (\"*degree*\"C)\")) +\n  prettyplot + \n  annotate(\"text\", x = Inf, y = Inf, label = \"A\", hjust = 1.5, vjust = 1.5, size = 4, fontface = \"plain\") +\n  theme(legend.position = \"none\", aspect.ratio = 0.65, \n        axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())\n\np2 <- sens_cond %>% \n  dplyr::filter(t <= 365 & T_level == 1) %>% \n  ggplot(aes(x = t, y = I_input)) +\n  geom_line(linewidth = 0.75) +\n  geom_line(data = state_input_timeseries, aes(x = yday, y = I_input_mean, colour = state), linetype = \"dotted\", inherit.aes = F) +\n  scale_y_continuous(breaks = seq(0, 700, 100), limits = c(0, 610)) +\n  labs(y = expression(\"Irradiance (\"*mu*\"mol m\"^-2*\" s\"^-1*\")\")) +\n  prettyplot + \n  annotate(\"text\", x = Inf, y = Inf, label = \"B\", hjust = 1.5, vjust = 1.5, size = 4, fontface = \"plain\") +\n  theme(legend.position = \"none\", aspect.ratio = 0.65, \n        axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())\n\np3 <- sens_cond %>% \n  dplyr::filter(t <= 365 & T_level == 1) %>% \n  ggplot(aes(x = t, y = U_input)) +\n  geom_line(linewidth = 0.75) +\n  geom_line(data = state_input_timeseries, aes(x = yday, y = UV_input_mean, colour = state), linetype = \"dotted\", inherit.aes = F) +\n  scale_y_continuous(breaks = seq(0, 0.6, 0.1), limits = c(0, 0.55)) +\n  labs(y = expression(\"Water velocity (m\"^-1*\" s\"^-1*\")\")) +\n  prettyplot + \n  annotate(\"text\", x = Inf, y = Inf, label = \"C\", hjust = 1.5, vjust = 1.5, size = 4, fontface = \"plain\") +\n  theme(legend.position = \"none\", aspect.ratio = 0.65, \n        axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())\n\np4 <- sens_cond %>% \n  dplyr::filter(t <= 365 & T_level == 1) %>% \n  ggplot(aes(x = t, y = S_input)) +\n  geom_line(linewidth = 0.75) +\n  geom_line(data = state_input_timeseries, aes(x = yday, y = S_input_mean, colour = state), linetype = \"dotted\", inherit.aes = F) +\n  scale_y_continuous(breaks = seq(33.1, 36.8, 0.3), limits = c(34, 36.1)) +\n  labs(y = expression(\"Salinity (g L\"^-1*\")\")) +\n  prettyplot + \n  annotate(\"text\", x = Inf, y = Inf, label = \"D\", hjust = 1.5, vjust = 1.5, size = 4, fontface = \"plain\") +\n  theme(legend.position = \"none\", aspect.ratio = 0.65, \n        axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank())\n\npdata1 <- sens_cond %>% \n  dplyr::filter(t <= 365 & T_level == 1) %>% \n  mutate(Ni_input = set_units(Ni_input, \"mg m-3\") %>% set_units(\"umol L-1\") %>% drop_units(),\n         Am_input = set_units(Am_input, \"mg m-3\") %>% set_units(\"umol L-1\") %>% drop_units())\npdata2 <- state_input_timeseries %>% \n  mutate(Ni_input_mean = set_units(Ni_input_mean, \"mg m-3\") %>% set_units(\"umol L-1\") %>% drop_units(),\n         Am_input_mean = set_units(Am_input_mean, \"mg m-3\") %>% set_units(\"umol L-1\") %>% drop_units())\n\np5 <- pdata1 %>% \n  ggplot(aes(x = t, y = Ni_input)) +\n  geom_line(linewidth = 0.75) +\n  geom_line(data = pdata2, aes(x = yday, y = Ni_input_mean, colour = state), linetype = \"dotted\", inherit.aes = F) +\n  scale_y_continuous(breaks = seq(0, 5, 0.5), limits = c(0, 3)) +\n  labs(y = nitrate_lab) +\n  prettyplot + \n  annotate(\"text\", x = Inf, y = Inf, label = \"E\", hjust = 1.5, vjust = 1.5, size = 4, fontface = \"plain\") +\n  theme(legend.position = \"none\", aspect.ratio = 0.65, axis.title.x = element_blank())\n\np6 <- pdata1 %>% \n  ggplot(aes(x = t, y = Am_input)) +\n  geom_line(linewidth = 0.75) +\n  geom_line(data = pdata2, aes(x = yday, y = Am_input_mean, colour = state), linetype = \"dotted\", inherit.aes = F) +\n  scale_y_continuous(breaks = seq(0, 10, 0.25), limits = c(0, 1)) +\n  labs(y = ammonium_lab) +\n  prettyplot + \n  annotate(\"text\", x = Inf, y = Inf, label = \"F\", hjust = 1.5, vjust = 1.5, size = 4, fontface = \"plain\") +\n  theme(legend.position = \"none\", aspect.ratio = 0.65, axis.title.x = element_blank())\n\nplot_grid(\n  plot_grid(p1, p2, p3, p4, p5, p6, ncol = 2, align = \"hv\"),\n  ggdraw() + draw_label(\"Day of the year\", size = 12),\n  ncol = 1,\n  rel_heights = c(0.95, 0.05)\n)\n```\n\n::: {.cell-output-display}\n![Average temperatures in each state region (left, see Figure 2 for detail) and the two temperature curves used for sensitivity analysis (high and low, right).](manuscript_files/figure-html/fig-sens-altogether-1.png){#fig-sens-altogether fig-align='center' width=624}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nd_top_PL <- c(0.5, 1, 1.5, 2, 2.5, 3) # tar_read(d_top_PL, store = runs_store)\n\nIlim_cell <- runs_data %>% \n  list.files(full.names = T) %>% \n  str_subset(\"Ilim_cell\") %>% \n  purrr::map_dfr(arrow::read_parquet)\n\n# Ilim_means <- Ilim_cell %>% \n#   group_by(state, depth, yday) %>% \n#   reframe(I_lim = mean(I_lim, na.rm = T))\n# \n# ggplot(Ilim_means, aes(x = yday, y = I_lim, colour = depth)) +\n#   geom_line(linewidth = 0.75) +\n#   facet_wrap(facets = vars(state)) +\n#   theme_classic()\n\nIlim_means <- Ilim_cell %>% \n  group_by(state, depth) %>% \n  reframe(I_sd = sd(I_lim, na.rm = T),\n          I_lim = mean(I_lim, na.rm = T))\n\nggplot(Ilim_means, aes(x = state, y = I_lim, fill = depth, ymin = I_lim-I_sd, ymax = I_lim+I_sd)) +\n  geom_col(colour = \"black\", position = position_dodge(), width = 0.95) +\n  geom_errorbar(position = position_dodge(width = 0.95), width = 0.5) +\n  theme_classic()\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nIlim_cell <- Ilim_cell %>% \n  dplyr::filter(depth == \"2.5\") %>% \n  dplyr::select(-c(irradiance, depth, state)) %>% \n  merge(cell_coords, by = \"cell_no\")\n\n# var_rast <- terra::rast(list(x = Ilim_cell$longitude, y = Ilim_cell$latitude, z = Ilim_cell$I_lim))\n# crs(var_rast) <- \"+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0\"))\n```\n:::\n\n\n\nExtra stuff?\n\n# Results \n\nA total of 8143 were omitted for being too shallow to accommodate the 5.5 m macroalgae canopy, leaving 87275 cells.\n\n## Species parameterisation\n\n\n\n::: {#cell-fig-all-responses .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nlibrary(gridExtra)\nlibrary(grid)\n\nN_uptake <- file.path(spec_data, \"N_uptake.parquet\") %>% \n  read_parquet()\nS_response <- file.path(spec_data, \"S_response.parquet\") %>% \n  read_parquet()\nI_response <- file.path(spec_data, \"I_response.parquet\") %>% \n  read_parquet() %>% \n  mutate(depth_m = as.factor(depth_m))\nT_response <- file.path(spec_data, \"T_response.parquet\") %>% \n  read_parquet() %>% \n  mutate(species = factor(species, levels = c(\"taxi\", \"arma\")))\n\np1 <- ggplot(N_uptake, aes(x = uM, y = uptake_uM, linetype = form)) +\n  geom_line(linewidth = 0.75) +\n  labs(x = expression(\"Ambient concentration (\"*mu*\"M)\"), y = expression(\"Uptake rate (\"*mu*\"mol gDW\"^-1*\"d\"^-1*\")\")) +\n  scale_y_continuous(breaks = seq(0, 3.5, 0.05), limits = c(0, 0.30)) +\n  scale_x_continuous(breaks = seq(0, 30, 5), limits = c(0,25)) +\n  prettyplot + \n  theme(aspect.ratio = 0.75)\n\np2 <- ggplot(T_response, aes(x = temp, y = Tlim, colour = species)) +\n  geom_line(linewidth = 0.75) +\n  labs(x = expression(\"Temperature (\"*degree*\"C)\"), y = \"Relative growth\") +\n  scale_y_continuous(breaks = seq(0, 1, 0.2), limits = c(0,1)) +\n  scale_x_continuous(breaks = seq(0, 40, 5), limits = c(0,35)) +\n  prettyplot + \n  theme(aspect.ratio = 0.75)\n\np3 <- ggplot(I_response, aes(x = light, y = Ilim, linetype = as.factor(depth_m))) +\n  geom_line(linewidth = 0.75) +\n  facet_wrap(facets = vars(species)) +\n  labs(x = expression(\"Surface light (PPFD)\"), y = \"Relative growth\") +\n  scale_y_continuous(breaks = seq(0, 1, 0.2), limits = c(0,1)) +\n  scale_linetype_manual(values = c(\"solid\", \"dashed\", \"dotdash\", \"dotted\")) +\n  prettyplot + \n  theme(aspect.ratio = 0.75, strip.text = element_blank())\n\np4 <- ggplot(S_response, aes(x = sali, y = Slim)) +\n  geom_line(linewidth = 0.75) +\n  labs(x = expression(\"Salinity (g L\"^-1*\")\"), y = \"Relative growth\") +\n  scale_y_continuous(breaks = seq(0, 1, 0.2), limits = c(0,1)) +\n  scale_x_continuous(breaks = seq(0, 60, 5), limits = c(19,45)) +\n  prettyplot + \n  theme(aspect.ratio = 0.75)\n\np1 <- p1 + annotate(\"text\", x = Inf, y = Inf, label = \"A\", hjust = 1.5, vjust = 1.5, size = 4)\np2 <- p2 + annotate(\"text\", x = Inf, y = Inf, label = \"B\", hjust = 1.5, vjust = 1.5, size = 4)\np3 <- p3 + annotate(\"text\", x = Inf, y = Inf, label = \"C\", hjust = 1.5, vjust = 1.5, size = 4)\np4 <- p4 + annotate(\"text\", x = Inf, y = Inf, label = \"D\", hjust = 1.5, vjust = 1.5, size = 4)\n\nplot_grid(\n  plot_grid(p1, p2, p3, p4, ncol = 2, align = \"hv\"),\n  ncol = 1,\n  rel_heights = c(0.95, 0.05)  # Adjust these values to control spacing\n)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 24 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 312 rows containing missing values or values outside the scale range\n(`geom_line()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Graphs cannot be horizontally aligned unless the axis parameter is\nset. Placing graphs unaligned.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![all responses](manuscript_files/figure-html/fig-all-responses-1.png){#fig-all-responses fig-align='center' width=624}\n:::\n:::\n\n\n\n### Parameter sensitivity\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\nsens_arma <- file.path(spec_data, \"sensitivity_arma_calc_combTU.parquet\") %>% \n  read_parquet() #%>% \n  # dplyr::filter(!param %in% c(\"M_am\", \"C_am\", \"M_ot\", \"C_ot\"))\nexlude <- unique(sens_arma$param[abs(sens_arma$sens) < 0.01]) %>% as.character\nsens_arma <- sens_arma %>% \n  dplyr::filter(!param %in% c(exlude, \"M_am\", \"C_am\", \"M_ot\", \"C_ot\"))\nsens_arma$param <- droplevels(sens_arma$param)\n\nlevels(sens_arma$param)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"V_am\"  \"K_am\"  \"C_ni\"  \"Q_min\" \"Q_max\" \"mu\"    \"D_ve\"  \"T_opt\" \"T_min\"\n[10] \"T_max\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nexlude\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"M_ni\"  \"K_c\"   \"a_cs\"  \"S_opt\" \"S_min\" \"S_max\" \"h_a\"   \"h_b\"   \"h_c\"  \n[10] \"h_max\" \"DWWW\"  \"I_o\"  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Add axis labels\nparam.labs.arma <- c(\n  bquote(\"V\"[\"Am\"]), bquote(\"K\"[\"Am\"]),\n  # bquote(\"M\"[\"Ni\"]),\n  bquote(\"C\"[\"Ni\"]), bquote(\"Q\"[\"min\"]), bquote(\"Q\"[\"max\"]),\n  # bquote(\"K\"[\"c\"]),\n  bquote(mu), bquote(\"D\"[\"ve\"]),\n  # bquote(\"a\"[\"cs\"]), bquote(\"I\"[\"o\"]),\n  bquote(\"T\"[\"opt\"]), bquote(\"T\"[\"min\"]), bquote(\"T\"[\"max\"])\n  # bquote(\"S\"[\"opt\"]), bquote(\"S\"[\"min\"]), bquote(\"S\"[\"max\"]), bquote(\"h\"[\"a\"]), bquote(\"h\"[\"b\"]), bquote(\"h\"[\"c\"]), bquote(\"h\"[\"max\"]), \"DW:WW\"\n)\n\nsens_taxi <- file.path(spec_data, \"sensitivity_taxi_calc_combTU.parquet\") %>% \n  read_parquet()\nexlude <- unique(sens_taxi$param[abs(sens_taxi$sens) < 0.01]) %>% as.character\nsens_taxi <- sens_taxi %>% \n  dplyr::filter(!param %in% c(exlude, \"M_am\", \"C_am\", \"M_ot\", \"C_ot\"))\nsens_taxi$param <- droplevels(sens_taxi$param)\n\nlevels(sens_taxi$param)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"V_am\"  \"K_am\"  \"C_ni\"  \"Q_min\" \"Q_max\" \"K_c\"   \"mu\"    \"D_ve\"  \"T_opt\"\n[10] \"T_min\" \"T_max\"\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nexlude\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"M_ni\"  \"a_cs\"  \"S_opt\" \"S_min\" \"S_max\" \"h_a\"   \"h_b\"   \"h_c\"   \"h_max\"\n[10] \"DWWW\"  \"I_o\"  \n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n# Add axis labels\nparam.labs.taxi <- c(\n  bquote(\"V\"[\"Am\"]), bquote(\"K\"[\"Am\"]), \n  # bquote(\"M\"[\"Ni\"]), \n  bquote(\"C\"[\"Ni\"]), bquote(\"Q\"[\"min\"]), bquote(\"Q\"[\"max\"]), bquote(\"K\"[\"c\"]), bquote(mu), bquote(\"D\"[\"ve\"]), \n  # bquote(\"a\"[\"cs\"]), bquote(\"I\"[\"o\"]), \n  bquote(\"T\"[\"opt\"]), bquote(\"T\"[\"min\"]), bquote(\"T\"[\"max\"])\n  # bquote(\"S\"[\"opt\"]), bquote(\"S\"[\"min\"]), bquote(\"S\"[\"max\"]), bquote(\"h\"[\"a\"]), bquote(\"h\"[\"b\"]), bquote(\"h\"[\"c\"]), bquote(\"h\"[\"max\"]), \"DW:WW\"\n)\n```\n:::\n\n::: {#cell-fig-sensitivity-plot .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\np1 <- ggplot(dplyr::filter(sens_arma, !is.na(sens)), \n       aes(x = rev(param), y = sens, fill = as.factor(cult_dep), ymin = sens-sd, ymax = sens+sd), \n       alpha = 0.75) +\n  geom_col(position = position_dodge(), width = 0.95, colour = \"black\") +\n  geom_errorbar(position = position_dodge(width = 0.95), width = 0.5) +\n  coord_flip() +\n  scale_y_continuous(limits = c(-1.1, 1.1), breaks = seq(-1.5, 1.5, 0.2)) +\n  scale_x_discrete(limits = levels(sens_arma$param), labels = rev(param.labs.arma)) +\n  scale_fill_manual(values = rev(depths_pal)) +\n  labs(y = \"Total N sensitivity\", x = \"Parameter name\") +\n  prettyplot +\n  theme(axis.title.x = element_blank(), \n        axis.text.x = element_blank(), \n        axis.ticks.x = element_blank(),\n        aspect.ratio = 0.75) + \n  annotate(\"text\", x = Inf, y = Inf, label = \"A\", hjust = 1.5, vjust = 1.5, size = 4)\n\np2 <- ggplot(dplyr::filter(sens_taxi, !is.na(sens)), \n       aes(x = rev(param), y = sens, fill = as.factor(cult_dep), ymin = sens-sd, ymax = sens+sd), \n       alpha = 0.75) +\n  geom_col(position = position_dodge(), width = 0.95, colour = \"black\") +\n  geom_errorbar(position = position_dodge(width = 0.95), width = 0.5) +\n  coord_flip() +\n  scale_y_continuous(limits = c(-1.1, 1.1), breaks = seq(-1.5, 1.5, 0.2)) +\n  scale_x_discrete(limits = levels(sens_arma$param), labels = rev(param.labs.taxi)) +\n  scale_fill_manual(values = rev(depths_pal)) +\n  labs(y = \"Total N sensitivity\", x = \"Parameter name\") +\n  prettyplot + \n  theme(aspect.ratio = 0.75) + \n  annotate(\"text\", x = Inf, y = Inf, label = \"B\", hjust = 1.5, vjust = 1.5, size = 4)\n\nplot_grid(p1, p2, nrow = 2, align = \"hv\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 4 rows containing missing values or values outside the scale range\n(`geom_col()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Relative impact of increasing each model parameter for _Asparagopsis armata_ (A) and _Asparagopsis taxiformis_ (B) by 10% on total N removed. Colours show the different culture depths of 0.5 m (orange), 2.5 m (blue) and 5.0 m (grey) below the surface. Error bars show variability (SD) across the 12 months of a typical year in each state. ](manuscript_files/figure-html/fig-sensitivity-plot-1.png){#fig-sensitivity-plot fig-align='center' width=624}\n:::\n:::\n\n\n\n## Growth and bioremediation\n\nThe point of this section is to:\n\n* Show the most common limiting factor - overall, between species, temporally, geographically\n* Show growth/nitrogen removal - overall, between species, temporally, geographically\n\n### Growth lims\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\ncell_growth_lims_fnms <- file.path(runs_data, \"cell_growth\") %>% \n  list.files(full.names = T) %>% \n  str_subset(\"cell_growth_lims_abbrev\")\n\n# This gives you a daily growth limiter for every cell\narmata_lims <- map_dfr(cell_growth_lims_fnms, function(fnm) {\n  arrow::read_parquet(fnm) %>%\n    filter(species == \"armata\") %>%\n    mutate(t = as.integer(t), t = case_when(t > 365 ~ t-365, T ~ t)) %>% \n    distinct(cell_no, species, t, lim)\n})  %>% \n  merge(cell_coords, by = \"cell_no\")\n\n# This gives you the dominant growth limiters per cell per month\ndom_lims <- file.path(runs_data, \"cell_growth_dom_lims.parquet\") %>% \n  arrow::read_parquet() %>% \n  merge(cell_coords, by = \"cell_no\")\n\n# cell_growth_rate <- file.path(runs_data, \"cell_growth_rate.parquet\") %>% \n#   arrow::read_parquet()\n```\n:::\n\n\n\n#### _Asparagopsis armata_\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden  code-summary=\"See if there are any days where different lims are conflicting (different batches)\"}\nstat1 <- armata_lims %>% \n  filter(latitude > -32) %>% \n  group_by(species, cell_no, lim) %>% \n  reframe(perc_days = n()/365)\nstat1_T <- mean(stat1$perc_days[stat1$lim == \"T_lim\"])\nstat1_Q <- mean(stat1$perc_days[stat1$lim == \"Q_lim\"])\nstat1_I <- mean(stat1$perc_days[stat1$lim == \"I_lim\"])\n\nstat2 <- armata_lims %>% \n  filter(latitude <= -32) %>% \n  group_by(species, cell_no, lim) %>% \n  reframe(perc_days = n()/365)\nstat2_T <- mean(stat2$perc_days[stat2$lim == \"T_lim\"])\nstat2_Q <- mean(stat2$perc_days[stat2$lim == \"Q_lim\"])\nstat2_I <- mean(stat2$perc_days[stat2$lim == \"I_lim\"])\n```\n:::\n\n\n\nFor _A. armata_ grown at latitudes > -32$^\\circ$, a mean of \n127.2% of growing days were limited by temperature, \n42.5% were limited by nutrients, and \n2.8% were limited by light. \n\nFor _A. armata_ grown at latitudes < -32$^\\circ$, a mean of \n25.9% of growing days were limited by temperature, \n119.4% were limited by nutrients, and \n3.4% were limited by light. \n\n\n\n::: {#cell-fig-growth-lim-armata-hist .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\n(\n  p_dom_xy <- armata_lims %>% \n    filter(species == \"armata\") %>% \n    filter(latitude <= -30) %>% \n    # slice_sample(n = 3000) %>%\n    mutate(month = parse_date_time(t, orders = \"j\"),\n           month = factor(month(month), labels = month.name)) %>% \n    ggplot(aes(y = latitude, fill = lim, colour = lim)) +\n    geom_histogram(position = \"stack\", alpha = 0.75) +\n    facet_wrap(facets = vars(month)) +\n    theme_classic() +\n    scale_fill_manual(values = lims_pal) +\n    scale_colour_manual(values = lims_pal) +\n    labs(x = expression(\"Cells\"*%*%*\"number of days\"), y = \"Latitude\")\n)\n```\n:::\n\n::: {#cell-fig-growth-lim-armata .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\np_dom <- filter(dom_lims, species == \"armata\" & start == 1) %>% \n  ggplot(aes(x = longitude, y = latitude, fill = lim)) +\n  geom_tile() +\n  geom_sf(data = ozmap_data(data = \"states\"), inherit.aes = F) +\n  coord_sf(xlim = c(bounds[[\"AUS\"]][\"lonmin\"], bounds[[\"AUS\"]][\"lonmax\"]),\n           ylim = c(bounds[[\"AUS\"]][\"latmin\"], bounds[[\"AUS\"]][\"latmax\"])) +\n  scale_x_continuous(breaks = seq(100, 160, 5)) +\n  scale_y_continuous(breaks = seq(-5, -45, -5)) +\n  scale_color_brewer(palette = \"Dark2\") +\n  scale_fill_manual(values = lims_pal) +\n  labs(x = \"Longitude\", y = \"Latitude\") +\n  prettyplot + \n  theme(legend.position = \"top\")\n\np_dom\np_dom %+% filter(dom_lims, species == \"armata\" & start == 2)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 3)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 4)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 5)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 6)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 7)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 8)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 9)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 10)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 11)\np_dom %+% filter(dom_lims, species == \"armata\" & start == 12)\n```\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-1.png){#fig-growth-lim-armata-1 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-2.png){#fig-growth-lim-armata-2 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-3.png){#fig-growth-lim-armata-3 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-4.png){#fig-growth-lim-armata-4 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-5.png){#fig-growth-lim-armata-5 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-6.png){#fig-growth-lim-armata-6 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-7.png){#fig-growth-lim-armata-7 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-8.png){#fig-growth-lim-armata-8 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-9.png){#fig-growth-lim-armata-9 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-10.png){#fig-growth-lim-armata-10 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-11.png){#fig-growth-lim-armata-11 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-armata-12.png){#fig-growth-lim-armata-12 fig-align='center' width=624}\n:::\n:::\n\n\n\n#### _Asparagopsis taxiformis_\n\n\n\n::: {#cell-fig-growth-lim-taxiformis .cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\np_dom <- filter(dom_lims, species == \"taxiformis\" & start == 1) %>% \n  ggplot(aes(x = longitude, y = latitude, fill = lim)) +\n  geom_tile() +\n  geom_sf(data = ozmap_data(data = \"states\"), inherit.aes = F) +\n  coord_sf(xlim = c(bounds[[\"AUS\"]][\"lonmin\"], bounds[[\"AUS\"]][\"lonmax\"]),\n           ylim = c(bounds[[\"AUS\"]][\"latmin\"], bounds[[\"AUS\"]][\"latmax\"])) +\n  scale_x_continuous(breaks = seq(100, 160, 5)) +\n  scale_y_continuous(breaks = seq(-5, -45, -5)) +\n  scale_color_brewer(palette = \"Dark2\") +\n  scale_fill_manual(values = lims_pal) +\n  labs(x = \"Longitude\", y = \"Latitude\") +\n  prettyplot + \n  theme(legend.position = \"top\")\n\np_dom\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 2)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 3)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 4)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 5)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 6)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 7)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 8)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 9)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 10)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 11)\np_dom %+% filter(dom_lims, species == \"taxiformis\" & start == 12)\n```\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-1.png){#fig-growth-lim-taxiformis-1 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-2.png){#fig-growth-lim-taxiformis-2 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-3.png){#fig-growth-lim-taxiformis-3 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-4.png){#fig-growth-lim-taxiformis-4 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-5.png){#fig-growth-lim-taxiformis-5 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-6.png){#fig-growth-lim-taxiformis-6 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-7.png){#fig-growth-lim-taxiformis-7 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-8.png){#fig-growth-lim-taxiformis-8 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-9.png){#fig-growth-lim-taxiformis-9 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-10.png){#fig-growth-lim-taxiformis-10 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-11.png){#fig-growth-lim-taxiformis-11 fig-align='center' width=624}\n:::\n\n::: {.cell-output-display}\n![](manuscript_files/figure-html/fig-growth-lim-taxiformis-12.png){#fig-growth-lim-taxiformis-12 fig-align='center' width=624}\n:::\n:::\n\n\n\n### Growth ends\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\ncell_growth_end <- file.path(runs_data, \"cell_growth_end.parquet\") %>% \n  read_parquet() %>% \n  mutate(t_start = as.integer(lubridate::month(parse_date_time(x = t_start, orders = \"j\"))+1),\n         t_start = case_when(t_start == 13 ~ 1, t_start == 14 ~ 2, T ~ t_start)) %>% \n  mutate(species = as.factor(species)) %>% \n  merge(cell_coords, by = \"cell_no\")\n```\n:::\n\n\n\n## Growth scenarios\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code .hidden}\ncell_growth_lims <- find_read(file.path(runs_data, \"cell_growth\"), \"growth_lims\") %>% \n  dplyr::select(cell_no, start, species, lims) %>% \n  mutate(lims = as.factor(lims),\n         species = as.factor(species)) %>% \n  merge(cell_coords, by = \"cell_no\")\n```\n:::\n\n\n\nWhen compared with the base scenario, all species were able to remove the most nitrogen in the fish farm scenario, almost certainly because of the increase in ammonium concentration from (very low) background levels (Figure 42). *Asparagopsis armata* and *A. taxiformis* consistently removed more nitrogen in the fish farm scenario.\n\nDifferences in nitrogen removed by *Asparagopsis* were minimal in the estuary mouth scenario across all states (ranging from -2.1% to +2.5% of base). Similarly, in the shallow bay scenario, *Asparagopsis* was able to remove from 0.4 to 9.5$\\times$ more nitrogen. The deep water scenario showed mostly negative but relatively small changes from the base removal, with changes ranging from -36% removal by *A. taxiformis* in New South Wales to +16.2% removed by *A. armata* in northern Western Australia. \n\nFigure 42: Nitrogen removal for different scenarios compared to the base scenario. Colours show the different scenarios as fish farm (purple), deep water (green), estuary mouth (orange) and shallow bay (pink).\n\n# Acknowledgments\n\n# Supplementary material\n\n# References",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}